export const auth = {
  CATCH_TRY_AUTH_ERROR: "auth/CATCH_TRY_AUTH_ERROR",
  CATCH_LOGIN_ERROR: "auth/CATCH_LOGIN_ERROR",
  HANDLE_SUCCESS_LOGIN: "auth/HANDLE_SUCCESS_LOGIN",
  START_LOGIN: "auth/START_LOGIN"
};
