export const auth = {
  CATCH_TRY_AUTH_ERROR: "auth/CATCH_TRY_AUTH_ERROR",
  CATCH_ERROR: "auth/CATCH_ERROR",
  HANDLE_SUCCESS_LOGIN: "auth/HANDLE_SUCCESS_LOGIN",
  START_LOGIN: "auth/START_LOGIN",
  HANDLE_SUCCESS_LOG_OUT: "auth/HANDLE_SUCCESS_LOG_OUT"
};

export const users = {
  START_LOAD_USER: "users/START_LOAD_USER",
  HANDLE_SUCCESS_LOAD_USER: "users/HANDLE_SUCCESS_LOAD_USER",
  CATCH_ERROR: "users/CATCH_ERROR"
};
